### ISSUE TITLE
dark mode not updated correctly everywhere

### ISSUE THREAD

**Issue by Shin-703** [rarsm/rars#61]
* [x] Need to update the RARS tools which have forced white on them. #79 #80
* [x] Same for help menu. #65
* [x] And the message panes. #66
* [x] Also the open file option colors doesn't update when we change theme dynamically. #81
